/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Student;

import Business.Profiles.StudentProfile;
import Business.Courses.Course;
import Business.Courses.CourseOffering;
import Business.Utils.Utilities;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinm
 */
public class StudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentJPanel
     */
    public StudentJPanel() {
        initComponents();
    }
    private JPanel workArea;
    private Utilities utils;
    public StudentJPanel(JPanel workArea, Utilities utils) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.workArea = workArea;
        this.utils = utils;
        populateCoursesTable();
        showGraduateDlg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CoursesJTable = new javax.swing.JTable();
        btnManageCourse = new javax.swing.JButton();
        btnSearchCourse = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        graduate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        CoursesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course Title", "Course ID", "Course Credits", "Professor", "Semester", "Timing"
            }
        ));
        jScrollPane1.setViewportView(CoursesJTable);

        btnManageCourse.setBackground(new java.awt.Color(51, 255, 255));
        btnManageCourse.setText("Manage Courses");
        btnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseActionPerformed(evt);
            }
        });

        btnSearchCourse.setBackground(new java.awt.Color(51, 255, 255));
        btnSearchCourse.setText("Search Courses");
        btnSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCourseActionPerformed(evt);
            }
        });

        btnTranscript.setBackground(new java.awt.Color(51, 255, 255));
        btnTranscript.setText("View Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(51, 255, 255));
        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        graduate.setBackground(new java.awt.Color(0, 0, 0));
        graduate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        graduate.setForeground(new java.awt.Color(255, 255, 255));
        graduate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        graduate.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageCourse)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTranscript)
                                    .addComponent(btnSearchCourse))
                                .addGap(283, 283, 283)
                                .addComponent(graduate))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnLogOut)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnManageCourse)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchCourse))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(graduate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTranscript))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseActionPerformed
        // TODO add your handling code here:
        ManageCoursesJPanel managePanel = new ManageCoursesJPanel(workArea,utils);
        workArea.add("ManageCoursesPanel",managePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageCourseActionPerformed

    private void btnSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCourseActionPerformed
        // TODO add your handling code here:
        SearchCourseJPanel searchPanel = new SearchCourseJPanel(workArea,utils);
        workArea.add("SearchCoursesPanel",searchPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnSearchCourseActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
       TranscriptJPanel transcriptPanel = new TranscriptJPanel(workArea,utils);
        workArea.add("transcriptPanel",transcriptPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea); 

// TODO add your handling code here:
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        utils.doLogout();
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
        populateCoursesTable();
    }//GEN-LAST:event_formAncestorMoved

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        populateCoursesTable();
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CoursesJTable;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageCourse;
    private javax.swing.JButton btnSearchCourse;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JTextField graduate;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populateCoursesTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel dtm = (DefaultTableModel) CoursesJTable.getModel();
        dtm.setRowCount(0);
        
        StudentProfile student = utils.getCurrentStudent();
//        
        ArrayList<CourseOffering> courses = student.getCourses();
        if(courses!=null){
        for(var x : courses){
            Object[] row = new Object[6];
            row[0] = x.getCourse().getCourseTitle();
            row[1] = x.getCourse().getCourseID();
            row[2] = x.getCourse().getCourseCredits();
            row[3] = x.getProfessor().getName();
            row[4] = x.getSemester();
            row[5] = x.getTiming();
            dtm.addRow(row);
        }
        }
    }

    private void showGraduateDlg() {
//        throw new UnsupportedOperxationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if(utils.getCurrentStudent().isReadyToGrad()){
            graduate.setText("Congratulations you are Graduated!!!!!!!!!!");
        }
    }
}
