/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Main;

import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.Courses.CourseOffering;
import Business.Utils.EmailSender;
import UI.Admin.AdminJPanel;
import UI.Professor.ProfessorLandingJPanel;
import UI.Student.StudentJPanel;
import Business.Utils.Utilities;
import UI.Employer.EmployerLandingJPanel;
import UI.TranscriptEvaluator.EvaluatorLandingJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ameysatwe
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    private Business.Utils.Utilities utils;

    public LoginJPanel(Business.Utils.Utilities utils) {
        initComponents();
        this.utils = utils;
    }

    private JPanel workArea;

    LoginJPanel(JPanel workArea, Utilities utils) {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated
        // from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.utils = utils;
        this.workArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtLoginUName = new javax.swing.JTextField();
        txtLoginPWD = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        chkBtnShowPWD = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        forgotPwdBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(30, 29, 51));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtLoginUName.setMinimumSize(new java.awt.Dimension(100, 25));

        txtLoginPWD.setMinimumSize(new java.awt.Dimension(100, 25));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login ");

        btnLogin.setBackground(new java.awt.Color(51, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        chkBtnShowPWD.setForeground(new java.awt.Color(255, 255, 255));
        chkBtnShowPWD.setText("Show password");
        chkBtnShowPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBtnShowPWDActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Name");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        SignupButton.setBackground(new java.awt.Color(51, 255, 255));
        SignupButton.setText("Signup");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        forgotPwdBtn.setBackground(new java.awt.Color(51, 255, 255));
        forgotPwdBtn.setText("Forgot Password?");
        forgotPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtLoginUName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SignupButton)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoginPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forgotPwdBtn)
                            .addComponent(chkBtnShowPWD)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLoginUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtLoginPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBtnShowPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(SignupButton)
                    .addComponent(forgotPwdBtn))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void forgotPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPwdBtnActionPerformed
        // TODO add your handling code here:
        String userName = txtLoginUName.getText();
        if(userName.length()>0){
            Profile profile = utils.getProfileByUsername(userName);
            if(profile!=null){
            try{
            EmailSender.send(profile.getEmail(),"Your new password for digital education platform is here" , "Hello " + profile.getName() + " , \n\n\n\n Your new password to login is : Northeastern");
            
            utils.AddPasswordAndEncrypt(userName,"Northeastern".toCharArray());
            JOptionPane.showMessageDialog(this, "An email with your updated password was sent to your registered email id");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Email could not be sent, Please check your email or create a new account");
            }
            }
            else{
                JOptionPane.showMessageDialog(this, "Please use a username that exists in the system. Or signup to the system");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Please enter username");
        }
    }//GEN-LAST:event_forgotPwdBtnActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        // Manage login.

        String userName = txtLoginUName.getText();
        // String pwd = Arrays.toString(txtLoginPWD.getPassword());

        boolean validated = this.utils.ValidateLogin(userName, txtLoginPWD.getPassword());
        if (validated) {

            utils.setCurrentProfile(utils.getProfileByUsername(userName));
            Profile.ProfileType type = utils.getProfileByUsername(userName).getType();

            JOptionPane.showMessageDialog(this, type.toString().toLowerCase() + " logged in");

            NavigateAccordingtoRole(type);
        } else {
            JOptionPane.showMessageDialog(this, "Please check username and password.");
        }

        txtLoginUName.setText("");
        txtLoginPWD.setText("");
    }// GEN-LAST:event_btnLoginActionPerformed

    private void chkBtnShowPWDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkBtnShowPWDActionPerformed
        // TODO add your handling code here:
        if (chkBtnShowPWD.isSelected()) {
            txtLoginPWD.setEchoChar((char) 0);
        } else {
            txtLoginPWD.setEchoChar('*');
        }
    }// GEN-LAST:event_chkBtnShowPWDActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SignupButtonActionPerformed
        // TODO add your handling code here:
        SignupJPanel signupPanel = new SignupJPanel(workArea, utils);
        workArea.add("signupPanel", signupPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }// GEN-LAST:event_SignupButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignupButton;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkBtnShowPWD;
    private javax.swing.JButton forgotPwdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtLoginPWD;
    private javax.swing.JTextField txtLoginUName;
    // End of variables declaration//GEN-END:variables

    private void NavigateAccordingtoRole(Profile.ProfileType type) {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated
        // from
        // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        switch (type) {
            case PROFESSOR -> {
                ProfessorLandingJPanel professorPanel = new ProfessorLandingJPanel(workArea, utils);
                workArea.add("professorLanding", professorPanel);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
            }
            case STUDENT -> {
                StudentJPanel studentPanel = new StudentJPanel(workArea, utils);
                workArea.add("studentLanding", studentPanel);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
            }
            case ADMIN -> {
                AdminJPanel adminPanel = new AdminJPanel(workArea, utils);
                workArea.add("adminLanding", adminPanel);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
            }
            case EMPLOYER ->{
                EmployerLandingJPanel employPanel = new EmployerLandingJPanel(workArea,utils);
                workArea.add("employerlanding",employPanel);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
            }
            case EVALUATOR -> {
                EvaluatorLandingJPanel evalPanel = new EvaluatorLandingJPanel(workArea,utils);
                workArea.add("evalPanel",evalPanel);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
            }
            default -> {
                break;
            }
        }
    }
}