/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Employer;

import Business.Profiles.ProfessorProfile;
import Business.Profiles.StudentProfile;
import Business.Utils.Utilities;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ameysatwe
 */
public class EmployerLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployerLandingJPanel
     */
    public EmployerLandingJPanel() {
        initComponents();
    }
    private JPanel workArea;
    private Utilities utils;
    private ArrayList<ProfessorProfile> profs;
    public EmployerLandingJPanel(JPanel workArea,Utilities utils){
        initComponents();
        this.workArea = workArea;
        this.utils = utils;
        populateProfTable();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profTable = new javax.swing.JTable();
        updateRatingButton = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employer Landing");

        profTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Professor Name", "Rating"
            }
        ));
        jScrollPane1.setViewportView(profTable);

        updateRatingButton.setBackground(new java.awt.Color(51, 255, 255));
        updateRatingButton.setText("Update Rating");
        updateRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRatingButtonActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(51, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout)
                    .addComponent(updateRatingButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateRatingButton)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addGap(0, 288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRatingButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = profTable.getSelectedRow();
       if(selectedRowIndex<0){
           JOptionPane.showMessageDialog(this, "Please select a row to View");
           return;
       } 
       else {
    
        ProfessorProfile prof = profs.get(selectedRowIndex);
//        student.AssignGrade(profManageStudsCourseID.getText(), (Integer)tblStudents.getValueAt(selectedRowIndex, 2));
//        System.out.println(student.getGrade(profManageStudsCourseID.getText()));
        prof.setRepIndexFromEmployer((Integer)profTable.getValueAt(selectedRowIndex, 1));
        populateProfTable();
       }
    }//GEN-LAST:event_updateRatingButtonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTable profTable;
    private javax.swing.JButton updateRatingButton;
    // End of variables declaration//GEN-END:variables

    private void populateProfTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel dtm = (DefaultTableModel) profTable.getModel();
        
        dtm.setRowCount(0);
        
        profs = utils.getProfessors();
        for(var p:profs){
            Object[] row = new Object[2];
            row[0] = p.getName();
            row[1] = p.getReputationIndex();
            dtm.addRow(row);
        }
    }
}
