/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Professor;

import Business.Courses.Course;
import Business.Courses.CourseOffering;
import UI.Main.LoginJPanel;
import Business.Utils.Utilities;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ameysatwe
 */
public class ProfessorLandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorLandingJPanel
     */
    private Utilities utils;
    public ProfessorLandingJPanel(Utilities utils) {
        initComponents();
        
    }
    private JPanel workArea;
    public ProfessorLandingJPanel(JPanel WorkArea, Utilities utils) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.utils = utils;
        this.workArea = WorkArea;
        professorTitleLabel.setText("Welcome Professor : " + utils.getCurrentProfile().getName());
        populateCoursesTable();
        populateCourseOfferingsTable();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profAddCourseBtn = new javax.swing.JButton();
        profManageStudents = new javax.swing.JButton();
        ProfUpdateProfileBtn = new javax.swing.JButton();
        professorTitleLabel = new javax.swing.JLabel();
        profLogoutButton = new javax.swing.JButton();
        profTeachingHistoryBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurrentCourses = new javax.swing.JTable();
        ProfessorAddCourseScheduleBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseSchedules = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        profAddCourseBtn.setBackground(new java.awt.Color(51, 255, 255));
        profAddCourseBtn.setText("Add Course");
        profAddCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profAddCourseBtnActionPerformed(evt);
            }
        });

        profManageStudents.setBackground(new java.awt.Color(51, 255, 255));
        profManageStudents.setText("Manage Students");
        profManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profManageStudentsActionPerformed(evt);
            }
        });

        ProfUpdateProfileBtn.setBackground(new java.awt.Color(51, 255, 255));
        ProfUpdateProfileBtn.setText("Update Profile");
        ProfUpdateProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfUpdateProfileBtnActionPerformed(evt);
            }
        });

        profLogoutButton.setBackground(new java.awt.Color(51, 255, 255));
        profLogoutButton.setText("Logout");
        profLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profLogoutButtonActionPerformed(evt);
            }
        });

        profTeachingHistoryBtn.setBackground(new java.awt.Color(51, 255, 255));
        profTeachingHistoryBtn.setText("Teaching History");
        profTeachingHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profTeachingHistoryBtnActionPerformed(evt);
            }
        });

        tblCurrentCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Semester"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCurrentCourses);

        ProfessorAddCourseScheduleBtn.setBackground(new java.awt.Color(51, 255, 255));
        ProfessorAddCourseScheduleBtn.setText("Add Course Schedule");
        ProfessorAddCourseScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorAddCourseScheduleBtnActionPerformed(evt);
            }
        });

        tblCourseSchedules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Title", "Semester", "Class Size"
            }
        ));
        jScrollPane2.setViewportView(tblCourseSchedules);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Courses");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Schedules");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(professorTitleLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ProfessorAddCourseScheduleBtn)
                                    .addComponent(profTeachingHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProfUpdateProfileBtn)
                                    .addComponent(profAddCourseBtn)
                                    .addComponent(profLogoutButton))))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(professorTitleLabel)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profLogoutButton)
                        .addGap(18, 18, 18)
                        .addComponent(profAddCourseBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ProfessorAddCourseScheduleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(profManageStudents)
                        .addGap(17, 17, 17)
                        .addComponent(profTeachingHistoryBtn)
                        .addGap(19, 19, 19)
                        .addComponent(ProfUpdateProfileBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profAddCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profAddCourseBtnActionPerformed
        // TODO add your handling code here:
        
        // Show add courses panel here.
        ProfessorAddCourseJPanel addCoursePanel = new ProfessorAddCourseJPanel(workArea,utils);
        workArea.add("AddCoursePanel",addCoursePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_profAddCourseBtnActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        populateCoursesTable();
        populateCourseOfferingsTable();
    }//GEN-LAST:event_formAncestorAdded

    private void profManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profManageStudentsActionPerformed
        // TODO add your handling code here:
        ProfessorManageStudentsJPanel managePanel = new ProfessorManageStudentsJPanel(workArea,utils);
        workArea.add("AddCoursePanel",managePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_profManageStudentsActionPerformed

    private void ProfUpdateProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfUpdateProfileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfUpdateProfileBtnActionPerformed

    private void profTeachingHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profTeachingHistoryBtnActionPerformed
        // TODO add your handling code here:
        ProfessorTeachingHistoryJPanel historyJPanel = new ProfessorTeachingHistoryJPanel(workArea,utils);
        workArea.add("historyPanel",historyJPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_profTeachingHistoryBtnActionPerformed

    private void ProfessorAddCourseScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorAddCourseScheduleBtnActionPerformed
        // TODO add your handling code here:
        // Navigate to Course schedule
        ProfessorAddScheduleJPanel schedulePanel = new ProfessorAddScheduleJPanel(workArea,utils);
        workArea.add("AddSchedulePanel",schedulePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_ProfessorAddCourseScheduleBtnActionPerformed

    private void profLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profLogoutButtonActionPerformed
        // TODO add your handling code here:
        utils.doLogout();
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_profLogoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProfUpdateProfileBtn;
    private javax.swing.JButton ProfessorAddCourseScheduleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton profAddCourseBtn;
    private javax.swing.JButton profLogoutButton;
    private javax.swing.JButton profManageStudents;
    private javax.swing.JButton profTeachingHistoryBtn;
    private javax.swing.JLabel professorTitleLabel;
    private javax.swing.JTable tblCourseSchedules;
    private javax.swing.JTable tblCurrentCourses;
    // End of variables declaration//GEN-END:variables

    private void populateCoursesTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
          DefaultTableModel dtm = (DefaultTableModel) tblCurrentCourses.getModel();
          dtm.setRowCount(0);
          
          ArrayList<Course> cs = utils.getCurrentCourses();
          
          for(Business.Courses.Course course : cs){
              Object[] row = new Object[3];
              row[0] = course;
              row[1] = course.getCourseTitle();
              row[2] = course.getCourseCredits();
              
              dtm.addRow(row);
          }
    }   

    private void populateCourseOfferingsTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel dtm = (DefaultTableModel) tblCourseSchedules.getModel();
          dtm.setRowCount(0);
          
          ArrayList<CourseOffering> cs = utils.getCourseOfferingsforCurrentProf();
          
          for(Business.Courses.CourseOffering co : cs){
              Object[] row = new Object[4];
              row[0] = co.getCourse().getCourseID();
              row[1] = co.getCourse().getCourseTitle();
              row[2] = co.getSemester();
              row[3] = co.getClassSize();
              
              dtm.addRow(row);
          }
    }
}
